= Home network nice hostnames with dnsmasq and docker
:showtitle:
:page-navtitle: dnsmasq and docker
:page-excerpt: Installing dnsmasq with docker
:page-root: ../../../
:page-layout: post

It's a new year, and I've decided to start cleaning up my home network a bit.
I've been wanting to organize stuff for a while now, but never got around to it.
One of the things I wanted to do was play with dnsmasq.
I had heard that it could be used to easily set up hostnames for devices on a LAN,
which would organize some of my local bookmarks and make things easier to remember, categorize, etc.

== The old way - hosts file

Dnsmasq can handle DNS and DHCP,
but what I plan to use it for is creating nice hostnames for machines on the LAN.
For example, I have a Synology NAS, with a static IP set to 192.168.0.x.
Earlier, on my dev laptop, I added that to `/etc/hosts` with an entry like:

[source, bash]
----
192.168.0.x nas
----

This enables me to hit the NAS using the name `nas` in my web browser or from the command line,
if I need to ssh to it, or ping it, etc.

If you have a bunch of machines at home running a development webserver, mediawiki, plex, or whatever,
you can create 'real looking' hostnames for these as well.
For example `wiki.home` or `plex.home` or something like that.

This seems all well and good.
However, I have other machines which connect to the NAS as well -- my wife's laptop,
a non development laptop, etc.
I could create host files in all these machines,
making sure to use the same names (`nas`, `wiki.home`, etc) in all of them to avoid confusion,
but this is not an optimal solution.
It's not DRY, so if I decided to change the static IP of the NAS,
or decided to add a server or more static IPs,
I'd have to update the host files in all these machines.

Additionally, me and my wife both have non-jailbroken iphones, and my wife has an ipad.
I haven't looked into it too much,
but it sounded like it wasn't straighforward to edit a hosts file in these devices.

== dnsmasq

I'm not knowledgable in networking, so I looked for the easiest solution I could find.
It sounded like dnsmasq could do the job well without too much fuss.
Essentially, dnsmasq acts as a lightweight DNS server,
with the benefit that it can take a hosts file and "propagate" it.
It's not really a hosts file, but it's just as easily configured.
Incidentally, you could probably do all of this with a 'real' DNS server,
but when I looked into it a bit, and saw all this stuff regarding 'A' records and whatnot,
I figured I'd keep it as easy as possible and use dnsmasq.
Maybe in the future I'll learn me some DNS, but for now, this serves its purpose.

I planned to run dnsmasq on a small Ubuntu box which is always on and has a static IP.
Earlier, on my router, I was using google's dns (`8.8.8.8` and `8.8.4.4`).
All devices pointed to the router as their DNS server.
Using dnsmasq, conceptually, I'd point the router to the static IP of the machine running dnsmasq instead.
The devices would still point to the router, but now the router would get its DNS handled by the dnsmasq box.
The dnsmasq box forwards stuff it doesn't know about to google's dns.
So the dnsmasq box would hand out my custom addresses,
and it sounds like it performs some caching to boot,
for performance purposes (haven't tested this yet).

Anyway, basically dnsmasq gets inserted between the router and the google dns servers.
It handles the custom local hostnames I give it,
and hands off outside addresses to the google dns servers,
which are still used.

== dockerized dnsmasq

To make things more fun, I also decided to run dnsmasq in a docker container.
I've been trying to play with docker to familiarize myself with it.
The way I see it, the easiest way to play with docker is to install docker containers off dockerhub,
configure and mess with them.
This was a good opportunity to try things out since dnsmasq is something I was going to install anyway, 
and this way has the benefit of not cluttering the filesystem,
installing extra dependencies, etc.
There are readme files with most images which have instructions on how to install and run them,
so this helps people like me who don't know what they're doing.
And if I didn't like it,
I could blow away the container or just try another dnsmasq image off dockerhub.
Whatever the case, there were several dnsmasq images available,
and the one I chose to use was `storytel/dnsmasq` 
--primarily because there was an easy to follow tutorial written by the author 
https://blog.csainty.com/2016/09/running-dnsmasq-in-docker.html[here].

I ran almost everything in the tutorial verbatim, however there were some complications.

== Obstacles

Obstacle 1

First off, docker reported that port 53 was already in use on my linux box (which runs Ubuntu 14.04) and it stopped the container.
Running 
`ps -aux | grep dns` or `netstat -nltp | grep -i listen`
showed there was already a dnsmasq instance being run.
It turns out Ubuntu 14.04 runs a handicapped dnsmasq by default.
It runs a dnsmasq-base package, which is limited in certain ways.
It can be configured to play nicely, but I opted for the easy approach by just turning it off.
This is done by commenting it out in 
__/etc/NetworkManager/NetworkManager.conf__ 
(comment out the line with `dns=dnsmasq`).

See these references for some background details:

* http://askubuntu.com/questions/191226/dnsmasq-failed-to-create-listening-socket-for-port-53-address-already-in-use

* https://ubuntuforums.org/showthread.php?t=2218655

* http://superuser.com/questions/681993/using-dnsmasq-with-networkmanager

Obstacle 2

If you follow the tutorial and run the container without first setting up the config files in
__/etc/dnsmasq__,
the container just quits.
When you run
`docker ps`,
there's nothing there.
However if you run
`docker ps -a`,
you'll see the container exited.
This is just because docker containers normally run one thing and then exit happily with knowledge of a job well done.
One of the lines in the config,
`keep-in-foreground`
will keep the process going, which keeps the container running.
So adding the 0.base.conf file in the tutorial and then running the container will work as expected.
I guess I was just impatient.

After that, you just add addresses and IPs to your own config file(s) and dnsmasq will pick them up and propagate them.
If you edit the files, you will need to restart the docker container.

Here's how I configured things:

in __/etc/dnsmasq/1.home.conf:__

    address=/nas.home/192.168.0.254
    address=/another-machine.home/192.168.0.253
    ... (add more local hostnames here)


One thing I also added was:

`docker update --restart=always dnsmasq`

This just sets the container to restart, so when I restart the machine,
it also restarts the dnsmasq container.
If not, when that machine restarts for whatever reason like updates or what have you,
my home network will be brought to its knees because there will be no dns for anyone.

Obstacle 3

I initially used a made up domain called 
`.local` 
http://superuser.com/questions/704785/ping-cant-resolve-hostname-but-nslookup-can[This caused problems because of avahi].
Apparently the avahi daemon is already set to use
`.local`
by default and it was conflicting with my addresses.
I was getting problems where I could
`nslookup test.local`,
and I could
`dig @localhost test.local`,
and these would resolve ok.
However when I tried to 
`ping test.local`
or visit it in a web browser, it didn't work.
I chose
`.local`
just out of sheer coincidence, so instead of editing the avahi config,
I simply changed my addresses to use
`.home`
instead, and this fixed the problem.
While searching for answers, I saw other posts regarding problems with `.dev` too.
I TLDR'ed all that though and just avoided using `.dev` as well.

== Conclusion

After all this,
I can now hit my NAS and other custom local hostnames from all the devices on my home network 
(including iphones and ipad, and other devices which I wouldn't normally be able to edit host files in).
Not sure how much this will help me,
but it is definitely nicer to be able to bookmark urls with names like wiki.home instead of 
192.168.0.xyz.

Later, I plan to set up openVPN so I can VPN to my home network from my phone or remote laptops, etc.
Having these nice hostnames will make that a bit nicer as well.
There's probably going to be complications getting the DNS from the home network while being VPN'ed,
but I'll have to look at that when I get there.

