= Using SSL with MySQL in Rails
:showtitle:
:page-navtitle: Using SSL with MySQL
:page-excerpt: 
:page-root: ../../../
:page-layout: post
:page-categories: mysql ssl rails

Haven't found a ton of articles showing how to configure a Rails app to connect to MySQL using SSL.

[NOTE]
.SSL vs TLS
====
MySQL can use various versions of transport security such as TLSv1, TLSv1.1, etc. as well as 
different cipher types.
SSL is considered insecure, and connection testing to the db showed it was using TLS.
However the entire discussion below refers to encrypted connections using the blanket term "SSL"
because the MySQL syntax refers to everything as SSL.
====

MySQL has different certificate authentication 'levels'.

|===
|Account option |Description

|REQUIRE NONE
|No certificates required by account, username/password is sufficient

|REQUIRE SSL
|Requires presentation of CA certificate file which matches the MySQL server's CA certificate file

|REQUIRE X509
|Requires presentation of CA certificate file, account certificate and key files.
Certificate must have been generated by the CA certificate.

|REQUIRE SUBJECT
|Requires presentation of CA certificate file, account certificate and key files.
Certificate must have been generated by the CA certificate.
Also verifies that the account certificate contains specific info, such as email address, etc.

|===

[IMPORTANT]
.User PKI authentication
====
PKI authentication in MySQL requires certificate files and cannot currently handle reading
certificates from hardware token.
This is more geared towards using certificates for applications to connect to MySQL.
For a user to connect (with say certificates on a smart card) your best bet would be to get
PAM authentication working.
If using self-signed certs, you could generate certificates for users, and let them manage their
certificates, etc.
====

Since the webserver connects to MySQL using SSL with PKI certificates,
its account is not needed to use password and password expiration 
(defers to certificate expiration instead).

==== SSL Configuration and Procedures

.Procedure, Creation of account without SSL requirement
[source,sql]
----
CREATE USER 'some_guy' IDENTIFIED BY 'some_password';
----

.Procedure, Login without SSL requirement
[source,bash]
----
mysql -u some_guy -h 192.168.x.y -p # <1>
(enter password)
----
<1> Assumes the account was given GRANTs to log in from given IP

.Procedure, Creation of account with REQUIRE SSL
[source,sql]
----
CREATE USER 'some_guy_ssl' REQUIRE SSL;

# we can also edit an existing user to require ssl
ALTER USER 'some_guy' REQUIRE SSL;

# or remove the requirement
ALTER USER 'some_guy' REQUIRE NONE;
----

.Procedure, Login with SSL requirement
[source,bash]
----
mysql -u some_guy_ssl -h 192.168.x.y -p # <1>
(enter password)
ERROR 1045 (28000): Access denied for user 'some_guy_ssl' (using password: YES) # <2>

mysql -u some_guy -h 192.168.x.y --ssl-mode=verify_ca --ssl-ca=/path/to/ca.pem # <3>
----
<1> Assumes the account was given GRANTs to log in from given IP
<2> Login without ssl mode is not allowed
<3> The ca.pem certificate must match the ca.pem certificate configured by the MySQL server

[NOTE]
.CA certificate
====
By default, MySQL creates its own self signed certificates for CA, the server, and a client.
These are good for 10 years.
These certificates meet FIPS 140-2 standards for validated cryptographic modules
used in the context of provisioning digital certificates.
====

.Procedure, Creation of account with REQUIRE X509
[source,sql]
----
CREATE USER 'some_guy_509' REQUIRE X509;

# add X509 requirement to existing user
ALTER USER 'some_guy' REQUIRE X509;
----

.Procedure, Login with x509 requirement
[source,bash]
----
mysql -u some_guy_509 -h 192.168.x.y -p # <1>
(enter password)
ERROR 1045 (28000): Access denied for user 'some_guy_ssl' (using password: YES) # <2>

mysql -u some_guy -h 192.168.x.y --ssl-mode=verify_ca --ssl-ca=/path/to/ca.pem # <3>
ERROR 1045 (28000): Access denied for user 'some_guy_ssl' (using password: NO) # <4>

mysql -u some_guy -h 192.168.x.y --ssl-mode=verify_ca --ssl-ca=/path/to/ca.pem --ssl-cert=/path/to/cert.pem --ssl-key=/path/to/key.pem # <5>
----
<1> Assumes the account was given GRANTs to log in from given IP
<2> Login without ssl mode is not allowed
<3> The ca.pem certificate must match the ca.pem certificate configured by the MySQL server
<4> Login without x509 certificate is not allowed
<5> Login requires valid x509 certificate which was created using the CA configured by MySQL

.Procedure, Creation of account with REQUIRE SUBJECT
[source,sql]
----
CREATE USER 'some_guy_subject' REQUIRE SUBJECT 'CN=client/emailAddress=client@example.com';

# add subject requirement to existing user
ALTER USER 'some_guy' REQUIRE SUBJECT 'CN=client/emailAddress=client@example.com';
----

.Procedure, Login with x509 with subject requirement
[source,bash]
----
mysql -u some_guy_509 -h 192.168.x.y -p # <1>
(enter password)
ERROR 1045 (28000): Access denied for user 'some_guy_ssl' (using password: YES) # <2>

mysql -u some_guy -h 192.168.x.y --ssl-mode=verify_ca --ssl-ca=/path/to/ca.pem # <3>
ERROR 1045 (28000): Access denied for user 'some_guy_ssl' (using password: NO) # <4>

mysql -u some_guy -h 192.168.x.y --ssl-mode=verify_ca --ssl-ca=/path/to/ca.pem --ssl-cert=/path/to/cert.pem --ssl-key=/path/to/key.pem # <5>
----
<1> Assumes the account was given GRANTs to log in from given IP
<2> Login without ssl mode is not allowed
<3> The ca.pem certificate must match the ca.pem certificate configured by the MySQL server
<4> Login without x509 certificate is not allowed
<5> Login requires valid x509 certificate which was created using the CA configured by MySQL,
and the certificate must contain the specified values

.Procedure, Verification of connections using SSL within MySQL
[source,sql]
----
SELECT sbt.variable_value AS tls_version,
    t2.variable_value AS cipher,
    processlist_user AS user,
    processlist_host AS host
    FROM performance_schema.status_by_thread AS sbt
    JOIN performance_schema.threads AS t ON t.thread_id = sbt.thread_id
    JOIN performance_schema.status_by_thread AS t2 ON t2.thread_id = t.thread_id
    WHERE sbt.variable_name = 'Ssl_version' and t2.variable_name = 'Ssl_cipher' ORDER BY tls_version;

# <1>
+-------------+--------------------+-------------+-------------+
| tls_version | cipher             | user        | host        |
+-------------+--------------------+-------------+-------------+
|             |                    | root        | localhost   |
| TLSv1       | DHE-RSA-AES256-SHA | test        | 192.168.x.y |
+-------------+--------------------+-------------+-------------+
----
<1> tls_version and cipher will be blank if that connection is not using SSL

.Procedure, Verification of connection using SSL within Rails
[source,ruby]
----
(in rails console)

Model.connection # <1>
----
<1> Specified model will return its database connection info.
Connection options will display if it is connected through SSL

