= Logrotate and MySQL
:showtitle:
:page-navtitle: Logrotate and MySQL
:page-excerpt: Conciseness at the cost of readability
:page-root: ../../../
:page-layout: post
:page-categories: mysql logs logrotate

== Log Rotation
At work we use the community edition of MySQL 5.7.x. server (not the enterprise version).
Our environment is very secure, so we have to lock things down a lot manually.
Without getting too much into all that, we have requirements that force us to keep the MySQL
General log always turned on.
This might be surprising or shocking to some, and yes we do take a performance hit, but hey that's
a requirement for us.
As you may know, the general log captures _every query_ performed by the database.
In other words, *it's huge*.
Our application is not that large, not a lot of users (it's an internal application) but our log
grows by multiple GB per day.
To avoid filling up `/var/log` or wherever the general log is configured to reside, the logs
must be rotated and compressed.

=== RHEL6 logrotate
We use RHEL6 for our db server.
The default installation of MySQL 5.7 on RHEL provides a logrotate script which can perform
the log rotation daily.

=== Troubleshooting log rotation
If you run the logrotate command manually, it will perform the rotation on your logs, which may
not be desirable.
To perform a dry run, which doesn't actually make changes to files, you can use the debug mode

  logrotate -d /etc/logrotate.conf

note that you can run an individual log rotation script instead of using the main one in `/etc`
but since settings in individual scripts may be inheriting settings from the main one, I would
suggest trying that first.

=== SELinux
When troubleshooting I found out what my problem was:
I had configured my MySQL general log to reside in `/var/lib/mysql/`, and SELinux had policies
which prevented logrotation and syslog from running in directories other than `/var/log`.
I had configured the general log to be saved in /var/lib/mysql when I didn't know any better,
and not knowing where I should put the logs, I figured keeping them in the MySQL's home directory
would be safe.

